/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aula2a;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author SESI_SENAI
 */
public class Janela extends javax.swing.JFrame {

    ArrayList<Aluno> chamada = new ArrayList<>();

    public Janela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        campoNome = new javax.swing.JTextField();
        campoIdade = new javax.swing.JTextField();
        campoCpf = new javax.swing.JTextField();
        campoMatricula = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        botaoCadastra = new javax.swing.JButton();
        botaoLista = new javax.swing.JButton();
        botaoRemove = new javax.swing.JButton();
        botaoEditar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setText("Cadastro de Aluno");

        jLabel2.setText("Nome:");

        jLabel3.setText("CPF:");

        jLabel4.setText("Idade:");

        jLabel5.setText("Matrícula:");

        botaoCadastra.setBackground(new java.awt.Color(102, 255, 102));
        botaoCadastra.setText("Cadastra");
        botaoCadastra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCadastraActionPerformed(evt);
            }
        });

        botaoLista.setBackground(new java.awt.Color(0, 204, 204));
        botaoLista.setText("Listar");
        botaoLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoListaActionPerformed(evt);
            }
        });

        botaoRemove.setBackground(new java.awt.Color(255, 0, 0));
        botaoRemove.setText("Remover");
        botaoRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoRemoveActionPerformed(evt);
            }
        });

        botaoEditar.setBackground(new java.awt.Color(255, 255, 51));
        botaoEditar.setText("Editar");
        botaoEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEditarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel2)
                .addGap(19, 19, 19)
                .addComponent(campoNome, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel3)
                .addGap(27, 27, 27)
                .addComponent(campoCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(campoIdade, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(92, 92, 92)
                .addComponent(jLabel5)
                .addGap(6, 6, 6)
                .addComponent(campoMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(botaoLista, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(botaoCadastra)
                .addGap(33, 33, 33)
                .addComponent(botaoEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(botaoRemove))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel2))
                    .addComponent(campoNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel3))
                    .addComponent(campoCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(campoIdade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))))
                .addGap(24, 24, 24)
                .addComponent(botaoLista)
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botaoCadastra)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(botaoEditar))
                    .addComponent(botaoRemove)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoCadastraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCadastraActionPerformed
        if (verificaInfos()) {
            String nome = campoNome.getText();
            String cpf = campoCpf.getText();
            String matricula = campoMatricula.getText();
            int idade = Integer.parseInt(campoIdade.getText());

            if (verificaCPF(cpf)) {
                JOptionPane.showMessageDialog(null, "Esse CPF já está cadastrado!");
            } else {
                Aluno a = new Aluno(matricula);
                a.setNome(nome);
                a.setIdade(idade);
                a.setCpf(cpf);
                chamada.add(a);
                campoNome.setText(null);
                campoCpf.setText(null);
                campoMatricula.setText(null);
                campoIdade.setText(null);
                JOptionPane.showMessageDialog(null, "Aluno cadastrado com sucesso!");
            }

        } else {
            JOptionPane.showMessageDialog(null, "Digite as informações corretamente!");
        }
    }//GEN-LAST:event_botaoCadastraActionPerformed
    public boolean verificaInfos() {
        if (campoNome.getText().equals("") || campoCpf.getText().equals("") || campoMatricula.getText().equals("") || campoIdade.getText().equals("")) {
            return false;
        }
        try {
            Integer.parseInt(campoIdade.getText());
        } catch (Exception e) {
            return false;
        }
        return true;
    }

    public boolean verificaCPF(String cpf) {
        for (Aluno a : chamada) {
            if (a.getCpf().equals(cpf)) {
                return true;
            }
        }
        return false;
    }

    private void botaoListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoListaActionPerformed
        String mensagem = "Alunos\n";
        for (Aluno a : chamada) {
            mensagem += "Nome: " + a.getNome() + "\n";
            mensagem += "Idade: " + a.getIdade() + "\n";
            mensagem += "Matrícula: " + a.getMatricula() + "\n";
            mensagem += "CPF: " + a.getCpf() + "\n";
            mensagem += "--------------------------\n";
        }
        JOptionPane.showMessageDialog(null, mensagem);
    }//GEN-LAST:event_botaoListaActionPerformed

    private void botaoRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoRemoveActionPerformed
        String cpf = JOptionPane.showInputDialog("Digite o CPF que deseja remover.");
        String mensagem = "CPF não encontrado!";
        for (Aluno a : chamada) {
            if (cpf.equals(a.getCpf())) {
                chamada.remove(a);
                mensagem = "O aluno " + a.getNome() + " foi removido!";
                break;
            }
        }
        JOptionPane.showMessageDialog(null, mensagem);
    }//GEN-LAST:event_botaoRemoveActionPerformed

    private void botaoEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEditarActionPerformed
        String cpf = JOptionPane.showInputDialog("Digite o CPF da pessoa que deseja editar.");
        String mensagem = "CPF não encontrado!";
        for (Aluno a : chamada) {
            if (cpf.equals(a.getCpf())) {
                String mensagemInput = "Qual informação deseja editar? (digite apenas UM número)\n\n"
                        + "Digite 1 para Nome;\n"
                        + "Digite 2 para CPF;\n"
                        + "Digite 3 para Idade;\n"
                        + "Digite 4 para Matrícula;";
                int input = 0;
                try {
                    input = Integer.parseInt(JOptionPane.showInputDialog(mensagemInput));
                } catch (Exception e) {
                    input = 0;
                }
                switch (input) {
                    case 1:
                        a.setNome(JOptionPane.showInputDialog("Digite o novo nome."));
                        mensagem = "O nome do aluno " + a.getNome() + " foi atualizado com sucesso!";
                        break;
                    case 2:
                        a.setCpf(JOptionPane.showInputDialog("Digite o novo CPF."));
                        mensagem = "O CPF do aluno " + a.getNome() + " foi atualizado com sucesso!";
                        break;
                    case 3:
                        a.setIdade(Integer.parseInt(JOptionPane.showInputDialog("Digite a nova idade.")));
                        mensagem = "A idade do aluno " + a.getNome() + " foi atualizada com sucesso!";
                        break;
                    case 4:
                        a.setMatricula(JOptionPane.showInputDialog("Digite a nova Matrícula."));
                        mensagem = "A matrícula do aluno " + a.getNome() + " foi atualizada com sucesso!";
                        break;
                    default:
                        mensagem = "Edição cancelada.";
                }
                break;
            }
        }
        JOptionPane.showMessageDialog(null, mensagem);
    }//GEN-LAST:event_botaoEditarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Janela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoCadastra;
    private javax.swing.JButton botaoEditar;
    private javax.swing.JButton botaoLista;
    private javax.swing.JButton botaoRemove;
    private javax.swing.JTextField campoCpf;
    private javax.swing.JTextField campoIdade;
    private javax.swing.JTextField campoMatricula;
    private javax.swing.JTextField campoNome;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
